<?php $__env->startSection('content'); ?>
<!-- Main Content-->
     <main class="main-content">
      <!--aboutUs section-->
      <section class="account">
        <div class="title">
          <div class="container">
            <h2><?php echo app('translator')->getFromJson('home.terms'); ?></h2>
          </div>
        </div>
        <div class="container">
          <div class="content">
            <div class="row">
              <div class="col-md-4">
                <div class="aboutImg"><img src="<?php echo e(asset('assets/imgs/aboutus/dental.png')); ?>"></div>
              </div>
              <div class="col-md-8" >
                <?php if( app()->getLocale()=='ar'): ?>
          

<p dir="RTL" style="margin:0in;margin-bottom:10.5pt;text-align:right;"><strong><span class="fs-12pt"style="">مقدمة</span></strong><strong><span class="fs-12pt"dir="LTR" style="">:</span></strong></p>
<p dir="RTL" style="margin:0in;margin-bottom:10.5pt;text-align:right;"><span class="fs-12pt"style="">هذه الاتفاقية هي عقد مبرم بين طبيب أسنان+ ومن يستخدم موقعها الإلكتروني على شبكة الإنترنت أوتطبيقات الهواتف الذكية سواء كان المستخدم مسجلاً أم لا، وبموافقة المستخدم على شروط الموقع يمكنه الدخول إليه واستخدامه حسب شروط الاتفاقية. وتعتبر هذه المقدمة جزءاً من هذه الاتفاقية والشروطهي</span><span class="fs-12pt"dir="LTR" style="">:</span></p>
<p dir="RTL" style="margin:0in;margin-bottom:10.5pt;text-align:right;"><strong><span class="fs-12pt"style="">شروط الاستخدام</span></strong><strong><span class="fs-12pt"dir="LTR" style="">:</span></strong></p>
<p dir="RTL" style="margin:0in;margin-bottom:10.5pt;text-align:right;"><span class="fs-12pt"style="">طبيب أسنان+ يخلي المسؤولية بأي حال من الأحوال الأضرار العرضية أو المباشرة أو غير المباشرة أو الخاصة أو العقابية أو النموذجية أو الناشئة، والتي قد تبرز نتيجة لاستخدامك أو عدم قدرتك على استخدام الموقع. وبمجرد استخدامك للموقع فانت توافق على</span><span class="fs-12pt"dir="LTR" style="">:</span><span class="fs-12pt"style="">&nbsp;الشروط والاحكام.</span></p>
<p dir="RTL" style="margin:0in;margin-bottom:10.5pt;text-align:right;"><span class="fs-12pt"style="">1- إن سرية المعلومات المعطاة والمقدمة بموجب هذا النظام هي من مسؤولية المشترك (المستخدم) وحده</span><span class="fs-12pt"dir="LTR" style="">.</span></p>
<p dir="RTL" style="margin:0in;margin-bottom:10.5pt;text-align:right;"><span class="fs-12pt"style="">2- إن المشترك (المستخدم) بمجرد استخدامه لهذا النظام يتنازل وبشكل مسبق ولا يقبل النقض عن أي شكاوى أو دعاوى أو مطالبات ناجمة عن استخدام موقع طبيب أسنان+وتطبيق الجوال.</span></p>
<p dir="RTL" style="margin:0in;margin-bottom:10.5pt;text-align:right;"><span class="fs-12pt"style="">3-إن موقع وتطبيقطبيب أسنان+ غير مسؤولة عن أي تأخير أو تردي في جودة الخدمة أو سوء أداء أو انقطاع في الخدمة لأي سبب كان، ويسقط المشترك (المستخدم) أي مطالبة له ضد طبيب أسنان+ بهذا الخصوص</span><span class="fs-12pt"dir="LTR" style="">.</span></p>
<p dir="RTL" style="margin:0in;margin-bottom:10.5pt;text-align:right;"><span class="fs-12pt"style="">4- أن يتعهد المشترك (المستخدم) بعدم إساءة استخدام البرنامج وعليه يتحمل وحده المسئولية لسوء استخدام البرنامج</span><span class="fs-12pt"dir="LTR" style="">.</span></p>
<p dir="RTL" style="margin:0in;margin-bottom:10.5pt;text-align:right;"><span class="fs-12pt"style="">5- المام (المشترك) المستخدم بالإجراءات والانظمة واللوائح للخدمة بشكلها الاعتيادي والتزامه بعدم مخالفة هذه الاجراءات والعمل على استيفاء متطلبات تقديم الخدمة</span><span class="fs-12pt"dir="LTR" style="">.</span></p>
<p dir="RTL" style="margin:0in;margin-bottom:10.5pt;text-align:right;"><strong><span class="fs-12pt"style="">الاستخدام</span></strong><strong><span class="fs-12pt"dir="LTR" style="">:</span></strong></p>
<p dir="RTL" style="margin:0in;margin-bottom:10.5pt;text-align:right;"><span class="fs-12pt"style="">أنت توافق على دخول واستخدام الموقع لأغراض مشروعة فقط، وعلى علم كامل بكل القوانين والأنظمة والقواعد والأحكام والشروط المتعلقة باستخدامك للموقع وتطبيق الجوال، وبمجرد دخولك إلى الموقع فإنك توافق على الامتناع عن</span><span class="fs-12pt"dir="LTR" style="">:</span></p>
<p dir="RTL" style="margin:0in;margin-bottom:10.5pt;text-align:right;"><span class="fs-12pt"style="">1- استخدام الموقع من أجل ارتكاب جريمة أو تشجيع الآخرين على التورط في أي تصرف قد يعد جريمة أو ينطوي على مسؤولية مدنية</span><span class="fs-12pt"dir="LTR" style="">.</span></p>
<p dir="RTL" style="margin:0in;margin-bottom:10.5pt;text-align:right;"><span class="fs-12pt"style="">2- إدخال أو نشر أي محتويات غير قانونية تتضمن تمييزاً أو تشهيراً أو إساءة أو قذف أو فاحشة ضد أي جهة كانت أو مواد إباحية</span><span class="fs-12pt"dir="LTR" style="">.</span></p>
<p dir="RTL" style="margin:0in;margin-bottom:10.5pt;text-align:right;"><span class="fs-12pt"style="">3- استخدام الموقع من أجل انتحال شخصيات أو أطراف أخرى</span><span class="fs-12pt"dir="LTR" style="">.</span></p>
<p dir="RTL" style="margin:0in;margin-bottom:10.5pt;text-align:right;"><span class="fs-12pt"style="">4- استخدام الموقع لتحميل أي مادة فيها برامج تحتوي على فيروسات أو ملفات تجسس أو أي شفرات حاسوبية أو ملفات أو برامج قد تعمل على تغيير أو إتلاف أو إعاقة عمل الموقع أو أي جهاز أو برنامج عائد إلى أي شخص يدخل إلى الموقع</span><span class="fs-12pt"dir="LTR" style="">.</span></p>
<p dir="RTL" style="margin:0in;margin-bottom:10.5pt;text-align:right;"><span class="fs-12pt"style="">5- تحميل أو إدخال أو إرسال أو بث لأي مواد لا يحق لك بثها بموجب أي قانون أو علاقة تعاقدية</span><span class="fs-12pt"dir="LTR" style="">.</span></p>
<p dir="RTL" style="margin:0in;margin-bottom:10.5pt;text-align:right;"><span class="fs-12pt"style="">6- تغيير أو إتلاف أو شطب أي محتوى على الموقع</span><span class="fs-12pt"dir="LTR" style="">.</span></p>
<p dir="RTL" style="margin:0in;margin-bottom:10.5pt;text-align:right;"><span class="fs-12pt"style="">7- تعطيل خطوط الاتصال الاعتيادية بأي شكل كان</span><span class="fs-12pt"dir="LTR" style="">.</span></p>
<p dir="RTL" style="margin:0in;margin-bottom:10.5pt;text-align:right;"><span class="fs-12pt"style="">8- الادعاءبالارتباط مع أو تمثيل أي شركة أو جمعية أو هيئة من دون أن تكون مخولاً بادعاء تلك العلاقة أو ذلك التمثيل</span><span class="fs-12pt"dir="LTR" style="">.</span></p>
<p dir="RTL" style="margin:0in;margin-bottom:10.5pt;text-align:right;"><span class="fs-12pt"style="">9- نشر أو بث أي إعلان أو مادة دعائية أو أي شكل من أشكال الترويج دون اتفاقية مسبقة</span><span class="fs-12pt"dir="LTR" style="">.</span></p>
<p dir="RTL" style="margin:0in;margin-bottom:10.5pt;text-align:right;"><span class="fs-12pt"style="">10- نشر أي مادة تتنافى أو تتعارض مع حقوق الملكية الفكرية للآخرين</span><span class="fs-12pt"dir="LTR" style="">.</span></p>
<p dir="RTL" style="margin:0in;margin-bottom:10.5pt;text-align:right;"><span class="fs-12pt"style="">11- جمع أو تخزين المعلومات الشخصية عن الآخرين</span><span class="fs-12pt"dir="LTR" style="">.</span></p>
<p dir="RTL" style="margin:0in;margin-bottom:10.5pt;text-align:right;"><strong><span class="fs-12pt"style="">تعديل الاتفاقية</span></strong><strong><span class="fs-12pt"dir="LTR" style="">:</span></strong></p>
<p dir="RTL" style="margin:0in;margin-bottom:10.5pt;text-align:right;"><span class="fs-12pt"style="">يحق لطبيب أسنان+ تعديل هذه الشروط والأحكام على أن يتم وضع إشعار بحدوث تعديلات على هذه الصفحة، وتدخل التعديلات حيز النفاذ بمجرد إحداثها، إن استخدامك المتكرر للموقع او تطبيقات الهواتف الذكية بعد إحداث تلك التعديلات يعني موافقتك على التعديلات، ويتعين عليك القيام بزيارات دورية لهذه الصفحة لمراجعة شروط وأحكام الاستخدام</span><span class="fs-12pt"dir="LTR" style="">.</span></p>
<p dir="RTL" style="margin:0in;margin-bottom:10.5pt;text-align:right;"><strong><span class="fs-12pt"style="">التسجيل</span></strong><strong><span class="fs-12pt"dir="LTR" style="">:</span></strong></p>
<p dir="RTL" style="margin:0in;margin-bottom:10.5pt;text-align:right;"><span class="fs-12pt"style="">بعض أجزاء الموقع أو تطبيقات الهواتف الذكية لا تفتح إلا للأعضاء المسجلين و/أو تتيح للمستخدم طلب الدعم أو الخدمات إلكترونياً عبر إدخال المعلومات الشخصية. أنت توافق على أن أي معلومات تقدم لنا عبر تلك الأجزاء هي معلومات كاملة ودقيقة، ولن تحاول دخول الموقع مستخدماً اسم شخص آخر، ولن تتبنى اسم مستخدم قد يراه طبيب أسنان+ غير مناسب</span><span class="fs-12pt"dir="LTR" style="">.</span></p>
<p dir="RTL" style="margin:0in;margin-bottom:10.5pt;text-align:right;"><strong><span class="fs-12pt"style="">إنهاء الاستخدام</span></strong><strong><span class="fs-12pt"dir="LTR" style="">:</span></strong></p>
<p dir="RTL" style="margin:0in;margin-bottom:10.5pt;text-align:right;"><span class="fs-12pt"style="">لطبيب أسنان+ كل الحق في إنهاء أو تعليق دخولك أو استخدامك لهذا الموقع أو تطبيقات الهواتف الذكية من دون إشعار مسبق وذلك بسبب انتهاكك لهذه الشروط أو القوانين المعمول أو بسبب أي تصرف قد يرى طبيب أسنان+ أنه مخالف للاتفاقيات الدولية والأعراف أو مضر بالآخرين، وفي حال الإنهاء لن يكون في إمكانك الدخول إلى الموقع أو تطبيقات الهواتف الذكية، وسوف طبيب أسنان+ كل وسيلة متاحة لتطبيق هذا المنع</span><span class="fs-12pt"dir="LTR" style="">.</span></p>
<p dir="RTL" style="margin:0in;margin-bottom:10.5pt;text-align:right;"><strong><span class="fs-12pt"style="">التعويض</span></strong><strong><span class="fs-12pt"dir="LTR" style="">:</span></strong></p>
<p dir="RTL" style="margin:0in;margin-bottom:10.5pt;text-align:right;"><span class="fs-12pt"style="">أنت توافق على الدفاع عن مصالح طبيب أسنان+ &nbsp;لدى أي جهة رسمية أو غير رسمية بسبب أي مطالبة مالية أو غير مالية نتجت عن انتهاكك لأي شرط من شروط هذه الاتفاقية ونتيجة لذلك فإنك تتحمل كل التكاليف المالية وغير المالية التي نتجت عن انتهاكك لأي شرط من شروط هذه الاتفاقية سواء أكانت تأميناً أو تعويضاً أو رسوماً أو أي تكاليف مالية أو غير مالية أخرى، وكل تسوية تقوم بها لدى أي جهة رسمية أو غير رسمية بسبب انتهاكك لأي شرط من شروط هذه الاتفاقية لا تصبح صحيحة ونافذة المفعول إلا بموافقة طبيب أسنان+ الصريحة والخطية لها</span><span class="fs-12pt"dir="LTR" style="">.</span></p>
<p dir="RTL" style="margin:0in;margin-bottom:10.5pt;text-align:right;"><strong><span class="fs-12pt"style="">التنازل عن الضمان</span></strong><strong><span class="fs-12pt"dir="LTR" style="">:</span></strong></p>
<p dir="RTL" style="margin:0in;margin-bottom:10.5pt;text-align:right;"><span class="fs-12pt"style="">أنت تفهم بوضوح وتوافق على أن استخدامك للموقع أو تطبيقات الهواتف الذكية أو أي مادة متاحة من خلاله هي خاضعة لمسؤوليتك الخاصة، ولا طبيب أسنان+ ولا أي من موظفيها ضمانة بأن الموقع أو تطبيقات الهواتف الذكية لن يتعرض للتوقف أو أنه سيكون خالياً من المشاكل أو الحذف أو الأخطاء، كما لا توجد ضمانة بشأن النتيجة التي ستحصل عليها جراء استخدامك للموقع او تطبيق الجوال، إن المحتويات والأدوات على الموقع مقدمة لك على حالها من دون ضمانات من أي نوع، سواء كانت صريحة أو ضمنية</span><span class="fs-12pt"dir="LTR" style="">.</span></p>
<p dir="RTL" style="margin:0in;margin-bottom:10.5pt;text-align:right;"><span class="fs-12pt"dir="LTR" style="">&nbsp;</span></p>
<p dir="RTL" style="margin:0in;margin-bottom:10.5pt;text-align:right;"><strong><span class="fs-12pt"style="">إقرار</span></strong></p>
<p dir="RTL" style="margin:0in;margin-bottom:10.5pt;text-align:right;"><span class="fs-12pt"style="">إن عيادة كلية طب الأسنان في الجامعة هي عيادة تعليمية للطلبة تحت اشراف أكاديمي من (أخصائيين واستشاريين) مع العلم بأن على كافة المرضى المسجلين تلقى العلاج من قبل الطلبة.</span></p>
<p dir="RTL" style="margin:0in;margin-bottom:10.5pt;text-align:right;"><span class="fs-12pt"style="">حيث إن المرضى المرشحين لتلقي العلاج سوف يتم قبولهم واختيارهم من قبل الأخصائيين بعد التشخيص المبدئي (لا يشمل العلاج) للمريض.&nbsp;</span></p>
<p dir="RTL" style="margin:0in;margin-bottom:10.5pt;text-align:right;"><span class="fs-12pt"style="">إن الخدمة المقدمة قد تستوجب حضور المريض لعدة زيارات وإن مدة كل زيارة قد تتجاوز ساعتين.</span></p>
<p dir="RTL" style="margin:0in;margin-bottom:10.5pt;text-align:right;"><span class="fs-12pt"style="">وعلى كافة المرضى استيعاب أن فترة العلاج مرتبطة بتواجد الطلبة بالعيادة.</span></p>
<p dir="RTL" style="margin:0in;margin-bottom:8.0pt;text-align:right;line-height:105%;"><span class="fs-12pt">أتفهم أن تقييم الأسنان الذي سأتلقاه اليوم لا يمثل فحصًا أو فحصًا للأسنان أو رأيًا ثانيًا، وأنه ينبغي عليّ الاستمرار في رؤية طبيب أسنان للحفاظ على صحة الأسنان إلا إذا و / أو حتى أتلقى إشعارًا بأنني تم قبولي كمريض في مستشفى كلية طب الأسنان.</span></p>
<p dir="RTL" style="margin:0in;margin-bottom:8.0pt;text-align:right;line-height:105%;"><span class="fs-12pt"dir="LTR" style="line-height:105%;font-family:&quot;Midan&quot;,&quot;serif&quot;color:#333333;">&nbsp;</span></p>
<p dir="RTL" style="margin:0in;margin-bottom:8.0pt;text-align:right;line-height:105%;"><span class="fs-12pt">أفهم أيضًا الغرض من زيارتي لمستشفى كلية طب الأسنان.</span></p>
<p dir="RTL" style="margin:0in;margin-bottom:8.0pt;text-align:right;line-height:105%;"><span class="fs-12pt">سيتم تقييم عيادة الأسنان لقبولي كمريض في عيادة التدريس الجامعي. إذا كان التقييم لطبيب الأسنان يشير إلى أنني لن أكون مريضًا مناسبًا، يجب أن أطلب علاج الأسنان في مكان آخر.</span></p>
<p dir="RTL" style="margin:0in;margin-bottom:10.5pt;text-align:right;"><span class="fs-12pt"style="">فقط إذا كان طبيب الأسنان يعتقد أن احتياجاتي في طب الأسنان قد تتناسب مع احتياجات طلاب طب الأسنان الذين يقدمون العلاج في العيادة التعليمية، قد يحيلني طبيب الأسنان إلى عيادة الأشعة الفموية للحصول على صور إشعاعية عن طريق الفم (يتم أخذ الأشعة السينية). بناءً على التقييم لطبيب الأسنان وتقييمه / تصويري لأشعة، سيتم اتخاذ قرار نهائي بشأن ما إذا كنت مريضًا مناسبًا أم لا. سيتم إخباري بهذا القرار.</span></p>
<p dir="RTL" style="margin:0in;margin-bottom:10.5pt;text-align:right;"><span class="fs-12pt"dir="LTR" style="">&nbsp;</span></p>
<p dir="RTL" style="margin:0in;margin-bottom:10.5pt;text-align:right;"><strong><span>معلومات عامة والموافقة</span></strong></p>
<p dir="RTL" style="margin:0in;margin-bottom:10.5pt;text-align:right;"><strong><u><span class="fs-12pt"dir="LTR" style=""><span class="fs-12pt"style="text-decoration:none;">&nbsp;</span></span></u></strong></p>
<p dir="RTL" style="margin:0in;margin-bottom:8.0pt;text-align:right;line-height:105%;"><span class="fs-12pt">1- جامعة التدريس</span><span class="fs-12pt"dir="LTR" style="line-height:105%;font-family:&quot;Midan&quot;,&quot;serif&quot;color:#333333;">:</span></p>
<p dir="RTL" style="margin:0in;margin-bottom:10.5pt;text-align:right;"><span class="fs-12pt"style="">المستشفى في كلية طب الأسنان، هي مؤسسة تعليمية. الطلاب والمتدربين والمقيمين وغيرهم من المتخصصين في الرعاية الصحية للأسنان المتحالفة، تحت إشراف طبيب الأسنان بالكلية. قد يشارك في الرعاية كجزء من البرنامج التعليمي.</span></p>
<p dir="RTL" style="margin:0in;margin-bottom:10.5pt;text-align:right;"><span class="fs-12pt"style="">&nbsp;</span></p>
<p dir="RTL" style="margin:0in;margin-bottom:8.0pt;text-align:right;line-height:105%;"><span class="fs-12pt">2- تصريح المعلومات</span><span class="fs-12pt"dir="LTR" style="line-height:105%;font-family:&quot;Midan&quot;,&quot;serif&quot;color:#333333;">:</span></p>
<p dir="RTL" style="margin:0in;margin-bottom:10.5pt;text-align:right;"><span class="fs-12pt"style="">المستشفى في كلية طب الأسنان مخوَّل لتقديم معلومات من سجل المريض لإحالة الطبيب / أطباء الأسنان وغيرهم فيما يتعلق بطلب المساعدة، أو المساعدة الطبية / طب الأسنان التي يحق للمريض الحصول عليها.</span></p>
<p dir="RTL" style="margin:0in;margin-bottom:10.5pt;text-align:right;"><span class="fs-12pt"style="">&nbsp;</span></p>
<h2 dir="RTL" style="margin:0in;margin-bottom:.0001pt;font-weight:normal;margin-top:2.0pt;text-align:right;line-height:105%;"><span class="fs-12pt">3- موافقة طب الأسنان</span></h2>
<p dir="RTL" style="margin:0in;margin-bottom:8.0pt;text-align:right;line-height:105%;"><span class="fs-12pt">المريض تحت رعاية أطباء الأسنان بالكلية. يوافق المريض أو ممثليه / ها على العلاجات أو الإجراءات (باستثناء الإجراءات الغازية التي تتطلب موافقة خاصة)، والفحوص الشعاعية، والصور الشفوية والإضافية التي يلتقطها شخص مرخص له، والإجراءات المختبرية، وإدارة التخدير الموضعي ، وغيرها من الخدمات المقدمة في إطار الخدمات العامة والخاصة تعليمات من أطباء الأسنان أعضاء هيئة التدريس أو غيرها من الكلية ، موظفي كلية طب الأسنان المساعدة في رعاية المرضى.</span></p>
<p dir="RTL" style="margin:0in;margin-bottom:8.0pt;text-align:right;line-height:105%;"><span class="fs-12pt"dir="LTR" style="line-height:105%;font-family:&quot;Midan&quot;,&quot;serif&quot;color:#333333;">&nbsp;</span></p>
<p dir="RTL" style="margin:0in;margin-bottom:10.5pt;text-align:right;"><span class="fs-12pt"style="">يتم قبول المرضى في العيادات التعليمية في الرعاية على أساس تقييم الصور الإشعاعية وفحص المريض. يعتمد القبول على احتياجات وقدرات الطلاب ورغباتهم واحتياجاتهم. سيتم إبلاغ المرضى الذين لم يتم قبولهم بعد موعد الفحص.</span></p>
<p dir="RTL" style="margin:0in;margin-bottom:10.5pt;text-align:right;"><span class="fs-12pt"style="">يتم تشجيع المرضى على مناقشة مخاوفهم وتوقعاتهم، وطرح الأسئلة لتعزيز أعلى مستوى من الرعاية. وتناقش مخاطر وفوائد الإجراءات الموصي بها وكذلك العلاج البديل بحيث يمكن اتخاذ قرارات واضحة. ومع ذلك، بسبب تباين استجابات المريض وقيود العلاج، لم يتم تقديم أي ضمان لأي إجراء.</span></p>
<p dir="RTL" style="margin:0in;margin-bottom:10.5pt;text-align:right;"><span class="fs-12pt"style="">يجب أن يكون المرضى متاحين لمدة 3 ساعات، في كثير من الأحيان مرتين في الأسبوع، ويجب أن يقدموا رقم هاتف حيث يمكن الوصول إليهم يوميًا. نظرًا لتخصيص المرضى للطلاب الذين يعملون تحت إشراف دقيق لأطباء الأسنان بالكلية، يستمر العلاج بوتيرة أبطأ بكثير من مكتب طبيب الأسنان الخاص، ولا يمكن ضمان إكمال الإجراءات خلال فترة زمنية محددة.</span></p>
<p dir="RTL" style="margin:0in;margin-bottom:10.5pt;text-align:right;"><span class="fs-12pt"dir="LTR" style="">&nbsp;</span></p>
<p dir="RTL" style="margin:0in;margin-bottom:10.5pt;text-align:right;"><strong><span class="fs-12pt"style="">اتفاقية خدمات طب الأسنان</span></strong></p>
<div style="margin:0in;margin-bottom:.0001pt;">
  <ul style="margin-bottom:0in;list-style-type: disc;margin-left:-0.5in;">
    <li style="margin:0in;margin-bottom:.0001pt;"><span class="fs-12pt"style="line-height:105%;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;font-size:15.0pt;color:#333333;">يجب على المرضى تقديم إشعار لمدة 24 ساعة على الأقل لإلغاء المواعيد؛ وإلا سوف تعتبر المواعيد "غياب". إذا فشل المريض في الظهور في المواعيد المحددة أو وصل متأخراً لأكثر من 20 دقيقة، فسيتم اعتبار المواعيد "غياب". موعدين من المواعيد "الغياب “سوف تتم مراجعة الملف وإمكانية حرمان المريض من إنهاء العلاج.</span></li>
  </ul>
</div>
<p dir="RTL" style="margin:0in;margin-bottom:8.0pt;text-align:right;line-height:105%;"><span class="fs-12pt"dir="LTR" >&nbsp;</span></p>
<div style="margin:0in;margin-bottom:.0001pt;">
  <ul style="margin-bottom:0in;list-style-type: disc;margin-left:-0.5in;">
    <li style="margin:0in;margin-bottom:.0001pt;"><span class="fs-12pt"style="line-height:105%;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;font-size:15.0pt;color:#333333;">جميع سجلات المرضى هي ملك كلية طب الأسنان</span></li>
  </ul>
</div>
<p style="margin:0in;margin-bottom:8.0pt;margin-top:0in;margin-right:0in;margin-left:.5in;line-height:105%;"><span class="fs-12pt"style="font-size:13px;line-height:105%;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;color:black;">&nbsp;</span></p>
<p dir="RTL" style="margin:0in;margin-bottom:10.5pt;text-align:right;"><strong><span class="fs-12pt"style="">اتفاقية</span></strong></p>
<p dir="RTL" style="margin:0in;margin-bottom:8.0pt;text-align:right;line-height:105%;"><span class="fs-12pt">كلية طب الأسنان والمريض أو ممثله، بموجب هذا الاتفاق. يشهد المريض أو ممثليه بأنه قد قرأ ووافق على شروط وأحكام الخدمة هذه وأنه هو المريض أو مخول له حسب الأصول بتنفيذ هذا الاتفاق والاتفاق نيابة عن المريض.</span></p>
<p dir="RTL" style="margin:0in;margin-bottom:10.5pt;text-align:right;"><span class="fs-12pt"dir="LTR" style="">&nbsp;</span></p>
<p dir="RTL" style="margin:0in;margin-bottom:10.5pt;text-align:right;"><strong><span class="fs-12pt"style="">تعليمات قبول هذه الشروط والأحكام</span></strong></p>
<p dir="RTL" style="margin:0in;margin-bottom:8.0pt;text-align:right;line-height:105%;"><span class="fs-12pt">المريض قاصر: يجب على الوالد أو الوصي قبول هذه الشروط والأحكام كممثل للمريض ما لم يُسمح للمريض قانونًا بالموافقة على الرعاية الطبية.</span></p>
<p dir="RTL" style="margin:0in;margin-bottom:10.5pt;text-align:right;"><strong><u><span class="fs-12pt"style=""><span class="fs-12pt"style="text-decoration:none;">&nbsp;</span></span></u></strong></p>
<p dir="RTL" style="margin:0in;margin-bottom:10.5pt;text-align:right;"><strong><span class="fs-12pt"style="">هام</span></strong></p>
<ol style="list-style-type: undefined;margin-left:-0.5in;">
  <li><span class="fs-12pt"style="line-height:105%;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;color:#333333;color:#333333;">قد تتطلب بعض العلاجات دفع رسوم رمزية للمواد أو الادوات ولكن لايزال طبيب الاسنان مجاني ( في المستشفيات الجامعية فقط).</span>
    <ol style="list-style-type: lower-alpha;">
      <li><span class="fs-12pt"style="line-height:105%;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;color:#333333;color:#333333;">المستخدمين من الجنسية السعودية يتطلب منهم ابراز الهوية الوطنية لدى &nbsp;استقبال المستشفى.</span></li>
      <li><span class="fs-12pt"style="line-height:105%;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;color:#333333;color:#333333;">المقيمين بالمملكة العربية السعودية يشترط ابراز هوية الإقامة و ان تكون سارية المفعول بتاريخ صالحية غير منتهي.</span></li>
    </ol>
  </li>
</ol>
<p dir="RTL" style="margin:0in;margin-bottom:8.0pt;text-align:right;line-height:105%;"><span class="fs-12pt">2- التواصل مع الطبيب في حال عدم التمكن من الحضور او الرغبة في الغاء الموعد.</span></p>
<p dir="RTL" style="margin:0in;margin-bottom:8.0pt;text-align:right;line-height:105%;"><span class="fs-12pt">3- طالب طب الاسنان غير مخول لتحويل المريض للمستشفيات او مراكز الرعاية الحكومية او الخاصة.</span></p>
<p dir="RTL" style="margin:0in;margin-bottom:8.0pt;text-align:right;line-height:105%;"><span class="fs-12pt">4- تجديد الموعد عن طريق تطبيق طبيب أسنان+ يسهل طريق علاجك. كما تتعرف على ملف طبيبك المعالج.</span></p>
<p dir="RTL" style="margin:0in;margin-bottom:8.0pt;text-align:right;line-height:105%;"><span class="fs-12pt">5- للأهمية التواصل بين المريض والطبيب فان رقم هاتفك المسجل سيظهر في تفاصل المواعيد.&nbsp;</span></p>
<p dir="RTL" style="margin:0in;margin-bottom:8.0pt;text-align:right;line-height:105%;"><span class="fs-12pt">6- طبيب أسنان+ يخلي مسؤوليته من أي خلاف ينشأ بين الطرفين</span></p>
<p dir="RTL" style="margin:0in;margin-bottom:8.0pt;text-align:right;line-height:105%;"><span class="fs-12pt">7- اللغة العربية هي المعتمدة في الشروط الاحكام أما اللغة الإنجليزية فتمثل مجرد ترجمة.</span></p>
<p dir="RTL" style="margin:0in;margin-bottom:8.0pt;text-align:right;line-height:105%;"><span class="fs-12pt">8- بياناتك المسجلة سوف تظهر في سجلات المواعيد لدى الطبيب او المريض للاطلاع على الحالة وذلكلأهميتها في قبول او رفض الطلب &nbsp;.</span></p>
<p dir="RTL" style="margin:0in;margin-bottom:8.0pt;text-align:right;line-height:105%;"><span class="fs-12pt">&nbsp;</span></p>
<p dir="RTL" style="margin:0in;margin-bottom:8.0pt;text-align:right;line-height:105%;"><strong><span class="fs-12pt">عيادات الأسنان الخاصة:</span></strong></p>
<ol style="list-style-type: undefined;margin-left:-0.5in;">
  <li><span class="fs-12pt"style="line-height:105%;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;font-size:15.0pt;color:#333333;">تم إضافة خدمات عيادات الاسنان الخاصة و التي تتطلب رسوم لتقديم خدامتها .</span></li>
  <li><span class="fs-12pt"style="line-height:105%;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;font-size:15.0pt;color:#333333;">طبيب أسنان+ يتيح للمستخدم حجز الموعد &nbsp;من خلال المنصة الالكترونية في عيادات الاسنان الخاصة و لكن لا يتحمل تكاليف الرسوم او العلاج المطلوب.</span></li>
  <li><span class="fs-12pt"style="line-height:105%;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;font-size:15.0pt;color:#333333;">طبيب أسنان+ يخلي مسؤوليته من أي خلاف قدينشأ بين المستخدم و مقدمي خدمات عيادة الاسنان الخاصة.</span></li>
  <li><span class="fs-12pt"style="line-height:105%;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;font-size:15.0pt;color:#333333;">حجزك لدى العيادات الخاصة تعني قبولك لشروط و أحكام و ضوابط المطبقة لدى العيادة بما تتضمن من رسوم الخدمات و طرق الدفع.</span></li>
</ol>
<p dir="RTL" style="margin:0in;margin-bottom:.0001pt;text-align:right;"><span class="fs-12pt"style="">&nbsp;</span></p>
<p dir="RTL" style="margin:0in;margin-bottom:.0001pt;text-align:right;"><span class="fs-12pt"style="">يحق لطبيب أسنان+ التعديل والإضافةوالحذف لاحد أنواع الحسابات او الإلغاء الحسابات او التعديل في احد البنود او اللوائح المذكورة اعلاه كما يراه مناسبا.</span></p>
<p dir="RTL" style="margin:0in;margin-bottom:10.5pt;text-align:right;"><span class="fs-12pt"style="">&nbsp;</span></p>
<p dir="RTL" style="margin:0in;margin-bottom:10.5pt;text-align:right;"><span class="fs-12pt"style="">تاريخالتحديث 2020/01/29</span></p>


					<?php elseif( app()->getLocale()=='en'): ?>
          
          
          <p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><strong><span class="fs-12pt"style=";">Terms and conditions</span></strong></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><strong><span class="fs-12pt"style=";">introduction:</span></strong></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><span class="fs-12pt"style=";">This agreement is a contract between a Dentist Pluss and those who use their website or phone applications, whether the user is registered or not, and with the user's consent to the terms of the site can access and use in accordance with the terms of the agreement. This introduction is part of this Agreement and the conditions are:</span></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><strong><span class="fs-12pt"style=";">Terms of use:</span></strong></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><span class="fs-12pt"style=";">A Dentist Pluss will in no way be liable for incidental, direct, indirect, special, punitive, typical or consequential damages, which may arise as a result of your use or inability to use the Site. By using the Site, you agree to: Terms and Conditions.</span></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><span class="fs-12pt"style=";">1. The confidentiality of information given and provided under this system is the sole responsibility of the subscriber.</span></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><span class="fs-12pt"style=";">2. The Subscriber (User), once using this system, waives in advance and does not accept to veto any complaints, claims or claims arising from the use of the Dentist Pluss website and mobile application.</span></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><span class="fs-12pt"style=";">3. The Dentist Pluss site and application is not responsible for any delay or deterioration in the quality of service, poor performance or interruption of the service for any reason whatsoever, and the subscriber (user) drops any claim against a Dentist Pluss in this regard.</span></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><span class="fs-12pt"style=";">4. The subscriber (the user) undertakes not to misuse the software and shall be solely responsible for the misuse of the software.</span></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><span class="fs-12pt"style=";">6. Familiar with the procedures, systems and regulations of the service in its normal form and its commitment not to violate these procedures and work to meet the requirements of providing the service.</span></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><strong><span class="fs-12pt"style=";">the use:</span></strong></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><span class="fs-12pt"style=";">You agree to access and use the Site solely for lawful purposes, and are fully aware of all laws, regulations, rules, terms and conditions relating to your use of the Site and the Mobile App, and once you access the Site you agree to refrain from:</span></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><span class="fs-12pt"style=";">1. Use the Site to commit a crime or encourage others to engage in any conduct that may be considered a crime or involve civil liability.</span></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><span class="fs-12pt"style=";">2. Introduce or publish any unlawful content that includes discrimination, defamation, abuse, defamation or obscenity against any party or pornographic material.</span></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><span class="fs-12pt"style=";">3. Use the Site to impersonate other persons or parties.</span></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><span class="fs-12pt"style=";">4. Use of the Site to download any material that contains software that contains viruses, spyware, computer codes, files or programs that may alter, damage or impede the operation of the Site or any device or software belonging to any person who accesses the Site.</span></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><span class="fs-12pt"style=";">5. Upload, enter, transmit or broadcast any material that you are not entitled to transmit under any law or contractual relationship.</span></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><span class="fs-12pt"style=";">6. Change, destroy or delete any content on the site.</span></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><span class="fs-12pt"style=";">7. Disable normal lines of communication in any form.</span></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><span class="fs-12pt"style=";">8. Claiming to associate with or represent any company, association or body without being authorized to claim that relationship or representation.</span></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><span class="fs-12pt"style=";">9. Publish or broadcast any advertisement, advertising material or any form of promotion without prior agreement.</span></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><span class="fs-12pt"style=";">10. Publish any material that is inconsistent with or contrary to the intellectual property rights of others.</span></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><span class="fs-12pt"style=";">11. Collect or store personal information about others.</span></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><strong><span class="fs-12pt"style=";">Amendment of the Convention:</span></strong></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><span class="fs-12pt"style=";">A Dentist Pluss has the right to amend these terms and conditions and to be notified of changes to this page. The amendments will enter into force as soon as they are made. Your repeated use of the site or mobile app after making these changes means you agree to the amendments, and you should periodically visit this page to review Terms and Conditions of Use.</span></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><strong><span class="fs-12pt"style=";">Registration:</span></strong></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><span class="fs-12pt"style=";">Some parts of the site or mobile app are open only to registered members and / or allow the user to request support or services electronically by entering personal information. You agree that any information you provide to us through those parts is complete and accurate, you will not attempt to access the site using someone else's name and will not adopt a username that a Dentist Pluss may deem inappropriate.</span></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><strong><span class="fs-12pt"style=";">Termination of use:</span></strong></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><span class="fs-12pt"style=";">A Dentist Pluss has the right to terminate or suspend your access or use of this website or mobile application without prior notice due to your violation of these terms or applicable laws or because of any action that a Dentist Pluss may find to be contrary to international agreements and customs or harmful to others. You will not be able to access the site or the mobile app, and a Dentist Pluss will have all the means available to apply this prohibition.</span></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><strong><span class="fs-12pt"style=";">Compensation:</span></strong></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><span class="fs-12pt"style=";">You agree to defend the interests of a Dentist Pluss at any official or unofficial authority due to any financial or non-financial claim resulting from your breach of any of the terms of this Agreement and as a result you incur all financial and non-financial costs resulting from your breach of any of these terms. The Agreement, whether insurance, indemnity, fees or any other financial or non-financial costs, and any settlement made by any official or non-official body because of a violation of any of the terms of this Agreement shall not become valid and effective only with the express and written consent of a Dentist Pluss.</span></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><strong><span class="fs-12pt"style=";">Waiver of Warranty:</span></strong></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><span class="fs-12pt"style=";">You clearly understand and agree that your use of the Site, the Mobile App or any material available through it is at your own risk, and no Dentist Pluss or any of its employees warrant that the Website or the Mobile App will not be interrupted or free from problems, deletion or errors, there is no guarantee as to the outcome of your use of the Site or the Mobile App. The contents and tools on the Site are provided to you without any warranties of any kind, either express or implied.</span></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><strong><span class="fs-12pt"style=";">Consent</span></strong></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><span class="fs-12pt"style=";">Hospital inCollege of Dentistry is a teaching institution. Treatment is provided by the student under the supervision of academic faculty.&nbsp;</span></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><span class="fs-12pt"style=";">Patients in the teaching clinics are accepted into care based upon assessment by the faculty dentist after initial screening (treatment not included).&nbsp;</span></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><span class="fs-12pt"style=";">The treatment provided will require the patient to attend several appointments for more than 2-hours.&nbsp;</span></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><span class="fs-12pt"style=";">The treatment procedures must be done during student clinic hours.&nbsp;</span></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><span class="fs-12pt"style=";">I understand that the Dental Assessment I will receive today does not constitute a dental check-up, Dental examination, or second opinion, and that I should continue to see a dentist to maintain my Dental Health unless and/or until I receive notice that I have been accepted as a patient in the hospital &nbsp;of College of Dentistry.&nbsp;</span></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><span class="fs-12pt"style=";">I also understand that the sole purpose of my visit to thehospital of College of Dentistry.&nbsp;</span></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><span class="fs-12pt"style=";">Dental Clinic today is to be assessed for admission as a patient in the Undergraduate Teaching Clinic. If the dentist’s visual assessment indicates I would not be an appropriate patient, I should seek dental treatment elsewhere.&nbsp;</span></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><span class="fs-12pt"style="font-size:1px;">&nbsp;</span></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><span class="fs-12pt"style=";">Only if the dentist who looks at my mouth believes my dental needs may match those of the dental students who provide treatment in the teaching clinic, will the dentist refer me the Oral Radiology Clinic to have oral radiographs (x-rays taken). Based upon the dentist’s visual assessment and his/her assessment of my radiographs, a final decision will be made about whether I am an appropriate patient. I will be notified of that decision.&nbsp;</span></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><span class="fs-12pt"style=";">&nbsp;</span></p>

<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><strong><span class="fs-12pt"style="">GENERAL INFORMATION AND CONSENT</span></strong></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><span class="fs-12pt"dir="RTL" style="">&nbsp;</span></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><span class="fs-12pt"style=";">&nbsp;</span></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><strong><span class="fs-12pt"style=";">A.&nbsp; TEACHING INSTITUTION:&nbsp;</span></strong></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><span class="fs-12pt"style=";">hospital in College of Dentistry, is a teaching institution. Students, interns, residents, and other allied dental healthcare professionals, under the supervision of faculty dentist. May participate in care as part of the educational program.</span></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><strong><span class="fs-12pt"style=";">b.&nbsp;RELEASE OF INFORMATION:&nbsp;</span></strong></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><span class="fs-12pt"style=";">&nbsp;</span></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><span class="fs-12pt"style=";">hospital in College of Dentistry is authorized to furnish information from the patient’s record to referring physician / dentists and others to the extent required in connection with the claim for aid, or medical / dental assistance to which the patient may be entitled.</span></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><strong><span class="fs-12pt"style=";">c.&nbsp;DENTAL CONSENT</span></strong></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><span class="fs-12pt"style=";">The patient is under the care of faculty dentists. The patient or his/her representative consents to treatments or procedure (except invasive procedures requiring special consent), radiographic examinations, intraoral and extra oral photographs taken by an authorized person, laboratory procedures, local anesthetic administration, and other service rendered under general and special instructions of faculty dentists or other from college, College of Dentistry personnel assisting in patient care.</span></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><span class="fs-12pt"style=";">Patients in the teaching clinics are accepted into care based upon assessment of radiographs and the intake screening. Acceptance is based upon needs and abilities of students, and desires, needs, and availability of patients. Patients who are not accepted subsequent to their screening appointment will be advised.</span></p>
<div style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;">
  <ol style="margin-bottom:0in;list-style-type: decimal;margin-left:-0.25in;">
    <li style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><span class="fs-12pt"style="">Patients are encouraged to discuss their concerns and expectations, and to ask questions to promote the highest level of care. The risks and benefits of recommended as well as alternative treatment procedures are discussed so that informed decisions may be made. However, due to the variability of patient responses and limitations of treatment, no guarantee or warranty is made for any procedure.</span></li>
     <li style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><span class="fs-12pt"style="">Patients must be available for 3-hour appointments, as often as twice a week, and must provide a phone number where they can be reached daily. Because patients are assigned to students working under the close supervision of faculty dentists, treatment proceeds at a significantly slower pace than in a private dentist’s office, and completion of procedures cannot be assured within a given period of time.</span></li>
  </ol>
</div>

<p style="margin-top:0in;margin-right:0in;margin-bottom:.0001pt;margin-left:.5in;line-height:107%;"><span class="fs-12pt"style=";">&nbsp;</span></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:.0001pt;margin-left:21.3pt;line-height:107%;"><span class="fs-12pt"style="">&nbsp;</span></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:.0001pt;margin-left:0in;line-height:107%;"><strong><span class="fs-12pt"style=";">DENTAL SERVICES AGREEMENT</span></strong></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:.0001pt;margin-left:0in;line-height:107%;"><strong><span class="fs-12pt"style=";">&nbsp;</span></strong></p>
<div style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;">
  <ol style="margin-bottom:0in;list-style-type: disc;margin-left:-0.25in;">
    <li style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><span class="fs-12pt"style="">Patients must give a minimum of 24-hours’ notice to cancel appointments; otherwise appointments will be considered “absent”. If patient fails to show up for scheduled appointments or arrive more than 20 minutes late, appointments will be considered “absent”. Two “absent” appointments constitute grounds for revising file and possible termination of treatment</span></li>
  </ol>
</div>
<p style="margin-top:0in;margin-right:0in;margin-bottom:.0001pt;margin-left:.5in;line-height:107%;"><span class="fs-12pt"style=";">&nbsp;</span></p>
<div style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;">
  <ul style="margin-bottom:0in;list-style-type: disc;margin-left:-0.25in;">
    <li style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><span class="fs-12pt"style="">All patient records are property of the College of Dentistry</span></li>
  </ul>
</div>
<p style="margin-top:0in;margin-right:0in;margin-bottom:.0001pt;margin-left:.5in;line-height:107%;"><span class="fs-12pt"style=";">&nbsp;</span></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:.25in;line-height:107%;"><span class="fs-12pt"style=";">&nbsp;</span></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><strong><span class="fs-12pt"style=";">AGREEMENT</span></strong></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><span class="fs-12pt"style=";">College of Dentistry and the patient or his/ her representative, hereby enter into this agreement. The patient or his/her representative certifies that he/she has read and accepted of this TERMS AND CONDITIONS OF SERVICE and is the patient or is duly authorized to execute and agreement on behalf of the patient.</span></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:.0001pt;margin-left:21.3pt;line-height:107%;text-align:center;"><strong><span class="fs-12pt"style=";">INSTRUCTIONS FOR ACCEPTING OF THIS TERMS AND CONDITIONS REQUIREMENTS</span></strong></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:21.3pt;line-height:107%;"><strong><span class="fs-12pt"style="">&nbsp;</span></strong></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><span class="fs-12pt"style=";">PATIENT IS A MINOR: &nbsp;The parent or guardian must be accepting of this TERMS AND CONDITIONS as Patient’s Representative unless the patient is legally allowed to consent to medical care.</span></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><strong><span class="fs-12pt"style=";">Important</span></strong></p>
<div style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;">
  <ol style="margin-bottom:0in;list-style-type: decimal;margin-left:undefined;">
    <li style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><span class="fs-12pt"style="">Some treatments may require a small fee for materials or tools, but the dentist is still free( in university’s hospital only).</span></li>
  </ol>
</div>
<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;text-indent:.5in;"><span class="fs-12pt"style=";">a.</span><span class="fs-12pt"style=";">user of Saudi nationality are required to show their national identity upon receiving the hospital.</span></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;text-indent:.5in;"><span class="fs-12pt"style=";">b. Residents of the Kingdom of Saudi Arabia, the residence ID must be presented and it must be valid with not expired.</span></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;text-indent:.5in;"><span class="fs-12pt"style=";">2. &nbsp;Communicate with your doctor if you cannot attend or wish to cancel the appointment.</span></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><span class="fs-12pt"style=";">3. A dental student is not authorized to transfer the patient to hospitals or government or private care centres.</span></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><span class="fs-12pt"style=";">4. Renew your appointment by applying a Dentist Pluss that will make your treatment easier.</span></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><span class="fs-12pt"style=";">A Dentist Pluss disclaims any dispute between the parties.</span></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><span class="fs-12pt"style=";">The Arabic language is approved in terms and conditions and English is just a translation.</span></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><span class="fs-12pt"style=";">Your recorded data will appear in the appointment records of the doctor or patient to see the case due to its importance in accepting or rejecting the application</span></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><strong><span class="fs-12pt"dir="RTL" style="">&nbsp;</span></strong></p>

<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><strong><span class="fs-12pt"style=";">Private dental clinics:</span></strong></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><span class="fs-12pt"style=";">1- Added private dental clinic services that require fees to provide their services.</span></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><span class="fs-12pt"style=";">2- A Dentist Pluss allows the user to book the appointment through the online platform in private dental clinics, but does not bear the costs of the required fees or treatment.</span></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><span class="fs-12pt"style=";">3- A Dentist Pluss disclaims any dispute that may arise between the user and the private dental clinic services providers.</span></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><span class="fs-12pt"style=";">4- Your reservation at private clinics means that you accept the terms, conditions and controls applied at the clinic, including service fees and payment methods.</span></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><span class="fs-12pt"style=";">&nbsp;</span></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><span class="fs-12pt"style=";">A Dentist Pluss has the right to modify, add and delete any type of account or cancel accounts or modify any terms mentioned above as he deems appropriate.</span></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><span class="fs-12pt"style=";">&nbsp;</span></p>
<p style="margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;"><span class="fs-12pt"style=";">Last updated 29/01/2020</span></p>

					<?php endif; ?>
              </div>
            </div>
           
          </div>
        </div>
      </section>
    </main>
    <!-- End Main Content-->
<?php $__env->stopSection(); ?>

<?php echo $__env->make('frontend.app', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?><?php /**PATH /home/bsamat/public_html/demo/dentistplus/resources/views/frontend/terms.blade.php ENDPATH**/ ?>